### ISSUE TITLE
Error:Type inference failed: Not enough information to infer parameter T in fun <T : View!> findViewById(p0: Int): T! Please specify it explicitly.

### ISSUE THREAD

**Issue by llleodeleon** [shazam/android-redux-sample#1]
I updated kotlin to the latest version and I got this error on the ViewBindingExtensions class

`ext.kotlin_version = '1.1.4-2'
`

Any idea on what to change?

**Comment by llleodeleon** [comment]
Solved using Kotlin Android Extensions, submitting PR

**Comment by fpezzato** [comment]
hi @leodeleon22! 
thanks for reporting and opening a PR!

Anyway, just to double check: I cannot reproduce your error on my laptop, I am using _Android Studio 3.0 Beta 2_, with _kotlin plugin 1.1.4-release-Studio3.0-2_. Also, as you mentioned, I have `ext.kotlin_version = '1.1.4-2'` in the project.

What AS version are you using?
thanks!
